[package]
name = "rust-blogpost-auth-async"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-web-httpauth = { git = "https://github.com/actix/actix-web-httpauth" }
chrono = { version = "0.4.10", features = ["serde"] }
derive_more = "0.99.2"
diesel = { version = "1.4.2", features = ["postgres","uuidv07", "r2d2", "chrono"] }
dotenv = "0.15.0"
futures = "0.3.1"
r2d2 = "0.8.8"
jsonwebtoken = "7"
bcrypt = "0.10"
serde = {version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
actix-service = "2.0.0"
alcoholic_jwt = "1.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
actix-rt = "1.0.0"
validator = { version = "0.12", features = ["derive"] }
